### ISSUE TITLE
Version 1.3.1 boot crash

### ISSUE THREAD

**Issue by zfms4188** [AET9RNAL/EcoEnergistics#5]
https://pastebin.com/5Gs5EX1u

xd pls

**Comment by AET9RNAL** [comment]
> https://pastebin.com/5Gs5EX1u
> 
> xd pls

What version of Mekanism you've tried  to launch the addon with? Because the log doesn't contain anything else other than the crash stacktrace

**Comment by zfms4188** [comment]
> > https://pastebin.com/5Gs5EX1u
> > xd pls
> 
> What version of Mekanism you've tried to launch the addon with? Because the log doesn't contain anything else other than the crash stacktrace

mekv10
https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2

**Comment by AET9RNAL** [comment]
> > > https://pastebin.com/5Gs5EX1u
> > > xd pls
> > 
> > What version of Mekanism you've tried to launch the addon with? Because the log doesn't contain anything else other than the crash stacktrace
> 
> mekv10
> https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2

MekV10 is unsupported, I should probably make a note somewhere on the page... Here is a [fork](https://www.curseforge.com/minecraft/mc-mods/mekanism-ecoenergistics-unofficial) that is compatible

**Comment by zfms4188** [comment]
> > > > https://pastebin.com/5Gs5EX1u
> > > > xd pls
> > > 
> > > 
> > > What version of Mekanism you've tried to launch the addon with? Because the log doesn't contain anything else other than the crash stacktrace
> > 
> > 
> > mekv10
> > https://github.com/sddsd2332/Mekanism-CE-Unofficial-1.12.2
> 
> MekV10 is unsupported, I should probably make a note somewhere on the page... Here is a [fork](https://www.curseforge.com/minecraft/mc-mods/mekanism-ecoenergistics-unofficial) that is compatible

ok！It's working properly
